#!/bin/bash

ulimit -c unlimited
alias qmake='qmake-qt5 -r'
alias qmaked='qmake-qt5 -r -config debug'

export QT_LOGGING_RULES="*.debug=true"

# Enable tab completion
source ~/.bashrc.d/git-completion.bash

# Change command prompt
source ~/.bashrc.d/git-prompt.sh

# colors!
red="\[\033[38;5;203m\]"
green="\[\033[38;05;38m\]"
blue="\[\033[0;34m\]"
reset="\[\033[0m\]"

export GIT_PS1_SHOWDIRTYSTATE=1

# '\u' adds the name of the current user to the prompt
# '\$(__git_ps1)' adds git-related stuff
# '\W' adds the name of the current directory
  #export PS1="$red\u$green\$(__git_ps1)$blue \W
  #$ $reset"

export PS1="[\u@\h$green\$(__git_ps1)$reset \W]\$ "

# DDS
export PATH=/opt/cyclone/bin:/opt/cyclone-cxx/bin:$PATH
